#Gateway Configuration Properties
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: greeting-microservice
          uri: 'http://localhost:8081'
          predicates:
            - Path=/greeting-microservice/**

#Tomcat Embedded Server Configuration
server:
  port: 8080

#Eureka Configuration Properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG