#Greeting Configuration Properties
spring:
  application:
    name: greeting-microservice








#Tomcat Embedded Server Configuration
server:
  port: 8081

#Eureka Configuration Properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
